language: csharp
dotnet: 3.1.100
solution: Netler.sln

jobs:
  include:
    - stage: test
      script:
        - dotnet restore
        - dotnet test

    - stage: deploy
      if: branch = master AND type = push AND fork = false AND tag IS blank
      script:
        - cd src/Netler
        - dotnet pack -c Release
        - cd bin/Release
        - dotnet nuget push *.nupkg -k $NUGET_KEY -s https://api.nuget.org/v3/index.json
        - cd $TRAVIS_BUILD_DIR
        - git tag -a v1.$TRAVIS_BUILD_NUMBER.0 -m v1.$TRAVIS_BUILD_NUMBER.0
        - git push --tags
