<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0;net8.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <PackageId>Netler.NET</PackageId>
    <Authors>Svan Jansson</Authors>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/svan-jansson/Netler.NET</RepositoryUrl>
    <Description>A library for cross-process method calls over TCP. For instance for calling .NET methods from Elixir (see https://hexdocs.pm/netler/). The library also contains a simple client that can be used to call a Netler server from another .NET application.</Description>
    <PackageIcon>netler.svg.png</PackageIcon>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageReleaseNotes Condition="Exists('$(MSBuildProjectDirectory)\..\..\release-notes.txt')">$([System.IO.File]::ReadAllText("$(MSBuildProjectDirectory)\..\..\release-notes.txt"))</PackageReleaseNotes>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" Version="2.5.192" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.13" />
    <PackageReference Include="Nerdbank.GitVersioning" Version="3.9.50" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\logo\netler.svg.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

</Project>
